# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate language-neutral and TypeScript conformance projections from v4 JSON Schema."""
from __future__ import annotations
import argparse, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "schema/mb-label-v4.schema.json"
JSON_OUT = ROOT / "schema/mb-label-v4.projection.json"
RUST_COPY = ROOT / "crates/mb-printer-core/schema/mb-label-v4.projection.json"
TS_OUT = ROOT / "crates/mb-printer-wasm/schema-types.generated.ts"

def build() -> tuple[str, str]:
    schema = json.loads(SCHEMA.read_text())
    defs = schema["$defs"]
    def effective(name: str) -> dict[str, list[str]]:
        node = defs[name]
        parts = [node, *node.get("allOf", [])]
        properties: set[str] = set()
        required: set[str] = set()
        for part in parts:
            if "$ref" in part:
                inherited = effective(part["$ref"].rsplit("/", 1)[1])
                properties.update(inherited["properties"]); required.update(inherited["required"])
            properties.update(part.get("properties", {})); required.update(part.get("required", []))
        return {"properties": sorted(properties), "required": sorted(required)}
    definitions = [item["$ref"].rsplit("/", 1)[1] for item in defs["element"]["oneOf"]]
    elements = [(name, next(part["properties"]["type"]["const"] for part in defs[name]["allOf"] if "properties" in part)) for name in definitions]
    projection = {
        "_license": "SPDX-License-Identifier: AGPL-3.0-or-later",
        "schemaId": schema["$id"], "root": {"properties": sorted(schema["properties"]), "required": sorted(schema["required"])},
        "elements": {discriminator: effective(name) for name, discriminator in elements}, "resources": effective("resource"),
    }
    encoded = json.dumps(projection, indent=2, sort_keys=True) + "\n"
    literals = " | ".join(json.dumps(discriminator) for _, discriminator in elements)
    ts = "// SPDX-License-Identifier: AGPL-3.0-or-later\n// Generated by scripts/generate_schema_projection.py; do not edit.\n"
    ts += f"export type MbLabelElementSchemaName = {literals};\n"
    ts += "export const mbLabelV4SchemaProjection = " + json.dumps(projection, separators=(",", ":")) + " as const;\n"
    return encoded, ts

def main() -> None:
    parser = argparse.ArgumentParser(); parser.add_argument("--check", action="store_true"); args = parser.parse_args()
    encoded, ts = build(); expected = {JSON_OUT: encoded, RUST_COPY: encoded, TS_OUT: ts}
    stale = [str(path.relative_to(ROOT)) for path, content in expected.items() if not path.exists() or path.read_text() != content]
    if args.check:
        if stale: raise SystemExit("stale schema projection: " + ", ".join(stale))
    else:
        for path, content in expected.items(): path.parent.mkdir(parents=True, exist_ok=True); path.write_text(content)

if __name__ == "__main__": main()
