#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate the lockfile-backed third-party license inventory."""
from __future__ import annotations

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
metadata = json.loads(subprocess.check_output(
    ["cargo", "metadata", "--locked", "--format-version", "1"], cwd=ROOT, text=True
))
workspace = set(metadata["workspace_members"])
rust = sorted(
    (p["name"], p["version"], p.get("license") or "UNKNOWN", p.get("repository") or "")
    for p in metadata["packages"] if p["id"] not in workspace
)
lock = json.loads((ROOT / "crates/mb-printer-wasm/package-lock.json").read_text())
npm = sorted(
    (path.removeprefix("node_modules/"), value.get("version", ""), value.get("license", "UNKNOWN"))
    for path, value in lock["packages"].items() if path
)
unknown = [f"Rust {n} {v}" for n, v, license, _ in rust if license == "UNKNOWN"]
unknown += [f"npm {n} {v}" for n, v, license in npm if license == "UNKNOWN"]
if unknown:
    raise SystemExit("dependencies without declared licenses: " + ", ".join(unknown))
lines = [
    "<!-- SPDX-License-Identifier: AGPL-3.0-or-later -->",
    "# Third-party dependency inventory",
    "",
    "Generated by `scripts/generate_dependency_inventory.py` from `Cargo.lock` and",
    "`crates/mb-printer-wasm/package-lock.json`. Dependency licenses remain the",
    "property of their respective authors; this project is distributed under",
    "AGPL-3.0-or-later.", "", "## Rust", "", "| Package | Version | Declared license | Repository |",
    "|---|---:|---|---|",
]
lines += [f"| {n} | {v} | {license} | {repo} |" for n, v, license, repo in rust]
lines += ["", "## npm development dependencies", "", "| Package | Version | Declared license |", "|---|---:|---|"]
lines += [f"| {n} | {v} | {license} |" for n, v, license in npm]
(ROOT / "THIRD_PARTY_LICENSES.md").write_text("\n".join(lines) + "\n")
