# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate language-neutral and TypeScript conformance projections from v4 JSON Schema."""
from __future__ import annotations
import argparse, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "schema/mb-label-v4.schema.json"
JSON_OUT = ROOT / "schema/mb-label-v4.projection.json"
RUST_COPY = ROOT / "crates/mb-printer-core/schema/mb-label-v4.projection.json"
TS_OUT = ROOT / "crates/mb-printer-wasm/schema-types.generated.ts"
RUST_OUT = ROOT / "crates/mb-printer-core/src/schema_types_generated.rs"

def build() -> tuple[str, str, str]:
    schema = json.loads(SCHEMA.read_text())
    defs = schema["$defs"]
    def effective(name: str) -> dict[str, list[str]]:
        node = defs[name]
        parts = [node, *node.get("allOf", [])]
        properties: set[str] = set()
        required: set[str] = set()
        for part in parts:
            if "$ref" in part:
                inherited = effective(part["$ref"].rsplit("/", 1)[1])
                properties.update(inherited["properties"]); required.update(inherited["required"])
            properties.update(part.get("properties", {})); required.update(part.get("required", []))
        return {"properties": sorted(properties), "required": sorted(required)}
    definitions = [item["$ref"].rsplit("/", 1)[1] for item in defs["element"]["oneOf"]]
    elements = [(name, next(part["properties"]["type"]["const"] for part in defs[name]["allOf"] if "properties" in part)) for name in definitions]
    projection = {
        "_license": "SPDX-License-Identifier: AGPL-3.0-or-later",
        "schemaId": schema["$id"], "root": {"properties": sorted(schema["properties"]), "required": sorted(schema["required"])},
        "elements": {discriminator: effective(name) for name, discriminator in elements}, "resources": effective("resource"),
    }
    encoded = json.dumps(projection, indent=2, sort_keys=True) + "\n"
    def type_name(name: str) -> str:
        return "MbLabel" + "".join(part.title() for part in name.replace("_", "-").split("-"))
    def ts_type(node: object) -> str:
        if not isinstance(node, dict): return "unknown"
        if "$ref" in node: return type_name(str(node["$ref"]).rsplit("/", 1)[1])
        if "const" in node: return json.dumps(node["const"], separators=(",", ":"))
        if "enum" in node: return " | ".join(json.dumps(value, separators=(",", ":")) for value in node["enum"])
        if "oneOf" in node: return " | ".join(f"({ts_type(value)})" for value in node["oneOf"])
        if "anyOf" in node: return " | ".join(f"({ts_type(value)})" for value in node["anyOf"])
        if "allOf" in node: return " & ".join(f"({ts_type(value)})" for value in node["allOf"])
        kind = node.get("type")
        if isinstance(kind, list): return " | ".join("null" if value == "null" else ts_type({**node, "type":value}) for value in kind)
        if kind == "string": return "string"
        if kind in ("integer", "number"): return "number"
        if kind == "boolean": return "boolean"
        if kind == "null": return "null"
        if kind == "array": return f"ReadonlyArray<{ts_type(node.get('items', {}))}>"
        if kind == "object" or "properties" in node:
            required = set(node.get("required", [])); fields = []
            for key, value in sorted(node.get("properties", {}).items()):
                fields.append(f"readonly {json.dumps(key)}{'?' if key not in required else ''}: {ts_type(value)}")
            additional = node.get("additionalProperties")
            if isinstance(additional, dict): fields.append(f"readonly [key: string]: {ts_type(additional)}")
            elif additional is True or (additional is None and node.get("unevaluatedProperties") is not False): fields.append("readonly [key: string]: unknown")
            return "{ " + "; ".join(fields) + " }"
        return "unknown"
    literals = " | ".join(json.dumps(discriminator) for _, discriminator in elements)
    ts = "// SPDX-License-Identifier: AGPL-3.0-or-later\n// Generated by scripts/generate_schema_projection.py; do not edit.\n"
    ts += f"export type MbLabelElementSchemaName = {literals};\n"
    for name, node in sorted(defs.items()): ts += f"export type {type_name(name)} = {ts_type(node)};\n"
    ts += f"export type MbLabelV4Document = {ts_type(schema)};\n"
    ts += "export const mbLabelV4SchemaProjection = " + json.dumps(projection, separators=(",", ":")) + " as const;\n"
    variants = []
    for _, discriminator in elements:
        variant = "".join(part.title() for part in discriminator.split("-"))
        variants.append(f"    #[serde(rename = {json.dumps(discriminator)})]\n    {variant},")
    rust = "// SPDX-License-Identifier: AGPL-3.0-or-later\n// Generated by scripts/generate_schema_projection.py; do not edit.\n"
    rust += "use serde::{Deserialize, Serialize};\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]\npub enum SchemaElementKind {\n"
    rust += "\n".join(variants) + "\n}\n"
    rust += "pub const SCHEMA_ID: &str = " + json.dumps(schema["$id"]) + ";\n"
    rust += "pub const ELEMENT_DISCRIMINATORS: &[&str] = &[\n"
    rust += "".join(f"    {json.dumps(value)},\n" for _, value in elements)
    rust += "];\n"
    return encoded, ts, rust

def main() -> None:
    parser = argparse.ArgumentParser(); parser.add_argument("--check", action="store_true"); args = parser.parse_args()
    encoded, ts, rust = build(); expected = {JSON_OUT: encoded, RUST_COPY: encoded, TS_OUT: ts, RUST_OUT: rust}
    stale = [str(path.relative_to(ROOT)) for path, content in expected.items() if not path.exists() or path.read_text() != content]
    if args.check:
        if stale: raise SystemExit("stale schema projection: " + ", ".join(stale))
    else:
        for path, content in expected.items(): path.parent.mkdir(parents=True, exist_ok=True); path.write_text(content)

if __name__ == "__main__": main()
