#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate Brother media definitions from the printer descriptors that ship
inside Brother's own Android application.

The descriptors are not redistributed: point this at a local extraction and it
writes the geometry we need into data/brother-media.json.

    unzip -o base.apk 'assets/ptd/*' -d /tmp/ptd
    python3 scripts/import_brother_ptd.py --ptd-dir /tmp/ptd/assets/ptd

Adding another Brother model is one line in MODELS.
"""

from __future__ import annotations

import argparse
import json
import re
from datetime import date
from pathlib import Path

# Our printer id -> the descriptor's dmdevicename.
MODELS = {
    "ql-1100": "Brother QL-1100",
    "ql-1110nwb": "Brother QL-1110NWB",
    "ql-1115nwb": "Brother QL-1115NWB",
}
DPI = 300
# "12mm x 2" and friends are the same roll printed several labels across.
MULTI_UP = re.compile(r"\sx\s\d+$")


def millimetres(dots: str) -> float:
    return round(int(dots) * 25.4 / DPI, 1)


def nominal(name: str) -> tuple[float, float] | None:
    """The mm the roll is sold as. Dot geometry rounds 29mm stock to 28.9."""
    values = [float(value) for value in re.findall(r"(\d+(?:\.\d+)?)mm", name)]
    if not values:
        return None
    if name.endswith("Dia"):
        return values[0], values[0]
    return (values[0], values[1]) if len(values) > 1 else (values[0], 0.0)


def identifier(name: str) -> str:
    if name.endswith("Dia"):
        return f"d{name.split('mm')[0]}"
    parts = [part.strip().removesuffix("mm") for part in name.split("x")]
    return "x".join(parts)


def papers(descriptor: dict) -> list[dict]:
    out = []
    for key in sorted(key for key in descriptor if key.startswith("Paper")):
        paper = descriptor[key]
        name = paper.get("szpapername_mm", "")
        if not name or MULTI_UP.search(name):
            continue
        continuous = paper.get("ntype") == "0x0a"
        round_media = name.endswith("Dia")
        sold_as = nominal(name)
        width_mm = sold_as[0] if sold_as else millimetres(paper["npaperwidthres"])
        height_mm = sold_as[1] if sold_as else millimetres(paper["npaperlengthres"])
        out.append(
            {
                "id": identifier(name),
                "name": name,
                "widthMm": width_mm,
                "heightMm": 0.0 if continuous else height_mm,
                "shape": "continuous" if continuous else "round" if round_media else "rectangle",
                "printableWidthDots": int(paper["nimageareawidthres"]),
                "printableLengthDots": int(paper["nimagearealengthres"]),
                "offsetRightDots": int(paper["wpinoffsetright"]),
                "feedMarginDots": int(paper["nphysicaloffsety"]),
            }
        )
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ptd-dir", type=Path, required=True, help="directory of assets/ptd/*.json")
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "crates/mb-printer-core/data/brother-media.json",
    )
    arguments = parser.parse_args()

    by_name = {}
    for path in sorted(arguments.ptd_dir.glob("*.json")):
        try:
            descriptor = json.loads(path.read_text())
        except (json.JSONDecodeError, UnicodeDecodeError):
            continue
        model = descriptor.get("Model", {}) if isinstance(descriptor, dict) else {}
        if name := model.get("dmdevicename"):
            by_name[name] = (path.name, descriptor)

    models, sources = {}, {}
    for printer_id, device_name in MODELS.items():
        if device_name not in by_name:
            raise SystemExit(f"no descriptor for {device_name}; check --ptd-dir")
        source, descriptor = by_name[device_name]
        models[printer_id] = papers(descriptor)
        sources[printer_id] = {"descriptor": source, "device": device_name, "headDots": descriptor["Model"]["dwheadpinnum"]}

    document = {
        "_comment": "Generated by scripts/import_brother_ptd.py from Brother's printer descriptors. Do not edit by hand.",
        "generatedOn": date.today().isoformat(),
        "dpi": DPI,
        "sources": sources,
        "models": models,
    }
    arguments.out.write_text(json.dumps(document, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {arguments.out} ({sum(len(v) for v in models.values())} media across {len(models)} models)")


if __name__ == "__main__":
    main()
