# SPDX-License-Identifier: AGPL-3.0-or-later
"""Attach deterministic license and generator provenance to generated bindings."""
from pathlib import Path
import json
import sys

root = Path(sys.argv[1])
header = "// SPDX-License-Identifier: AGPL-3.0-or-later\n// Generated by wasm-bindgen-cli 0.2.127; do not edit.\n"
for path in sorted((*root.glob("web/*.*s"), *root.glob("node/*.*s"))):
    text = path.read_text()
    if not text.startswith("// SPDX-License-Identifier:"):
        path.write_text(header + text)
provenance = {
    "generator": "wasm-bindgen-cli 0.2.127",
    "license": "AGPL-3.0-or-later",
    "source": "https://github.com/MakersBrain/mb-printer-sdk",
    "artifacts": ["web/mb_printer_wasm.js", "web/mb_printer_wasm_bg.wasm", "node/mb_printer_wasm.cjs"],
}
(root / "PROVENANCE.json").write_text(json.dumps(provenance, indent=2, sort_keys=True) + "\n")
