// SPDX-License-Identifier: AGPL-3.0-or-later
//! Media catalogue: which rolls, die-cut labels, and tapes a model can carry.
//!
//! Brother models come from `data/brother-media.json`, generated by
//! `scripts/import_brother_ptd.py` out of Brother's own printer descriptors, so
//! adding a model is an import rather than a transcription. The Phomemo
//! families ship no descriptor, so `data/phomemo-media.json` is maintained here.

use crate::capabilities::PrinterDefinition;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::sync::LazyLock;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MediaPreset {
    pub id: String,
    pub name: String,
    pub width_mm: f64,
    /// Zero for continuous stock, which the caller cuts to length.
    pub height_mm: f64,
    /// `rectangle`, `round`, or `continuous`.
    pub shape: String,
    /// Present for tape stock, so a model only offers the widths it accepts.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tape_width_mm: Option<u16>,
    /// Printable area and placement, where the source descriptor states them.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub printable_width_dots: Option<u32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub printable_length_dots: Option<u32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub offset_right_dots: Option<u32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub feed_margin_dots: Option<u32>,
}

#[derive(Deserialize)]
struct BrotherMedia {
    models: BTreeMap<String, Vec<MediaPreset>>,
}
#[derive(Deserialize)]
struct GroupedMedia {
    groups: BTreeMap<String, Vec<MediaPreset>>,
}

static BROTHER: LazyLock<BrotherMedia> = LazyLock::new(|| {
    serde_json::from_str(include_str!("../data/brother-media.json"))
        .expect("bundled Brother media parses")
});
static PHOMEMO: LazyLock<GroupedMedia> = LazyLock::new(|| {
    serde_json::from_str(include_str!("../data/phomemo-media.json"))
        .expect("bundled Phomemo media parses")
});

/// Printable width of the head, which no media may exceed.
pub fn head_width_mm(printer: &PrinterDefinition) -> Option<f64> {
    printer
        .width_bytes
        .map(|bytes| f64::from(bytes) * 8. * 25.4 / f64::from(printer.dpi))
}

/// Every media a model can carry. Brother descriptors are already per model;
/// the shared Phomemo groups are filtered by head width and tape width.
pub fn presets_for(printer: &PrinterDefinition) -> Vec<MediaPreset> {
    let group = printer.label_presets.as_deref().unwrap_or_default();
    if group == "dk" {
        return BROTHER.models.get(&printer.id).cloned().unwrap_or_default();
    }
    let Some(catalogue) = PHOMEMO.groups.get(group) else {
        return Vec::new();
    };
    let head = head_width_mm(printer);
    catalogue
        .iter()
        .filter(
            |preset| match (preset.tape_width_mm, printer.tape_widths.as_ref()) {
                (Some(width), Some(widths)) => widths.contains(&width),
                (Some(_), None) => false,
                _ => true,
            },
        )
        // Nothing wider than the head can be printed. On tape it is the tape
        // width that crosses the head, not the label length.
        .filter(|preset| {
            let across = preset.tape_width_mm.map_or(preset.width_mm, f64::from);
            head.is_none_or(|head| across <= head + 1.)
        })
        .cloned()
        .collect()
}

/// Names the media a printer reported. Die-cut wins over continuous, and both
/// orientations are tried, since a status reply describes the tape, not the label.
pub fn match_media(
    printer: &PrinterDefinition,
    width_mm: f64,
    height_mm: f64,
) -> Option<MediaPreset> {
    const TOLERANCE: f64 = 1.5;
    let close = |left: f64, right: f64| (left - right).abs() <= TOLERANCE;
    let presets = presets_for(printer);
    presets
        .iter()
        .find(|preset| {
            preset.height_mm > 0.
                && ((close(preset.width_mm, width_mm) && close(preset.height_mm, height_mm))
                    || (close(preset.width_mm, height_mm) && close(preset.height_mm, width_mm)))
        })
        .or_else(|| {
            presets
                .iter()
                .find(|preset| preset.height_mm == 0. && close(preset.width_mm, width_mm))
        })
        .cloned()
}
