// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by scripts/generate_schema_projection.py; do not edit.
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SchemaElementKind {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "image")]
    Image,
    #[serde(rename = "svg")]
    Svg,
    #[serde(rename = "line")]
    Line,
    #[serde(rename = "rectangle")]
    Rectangle,
    #[serde(rename = "ellipse")]
    Ellipse,
    #[serde(rename = "triangle")]
    Triangle,
    #[serde(rename = "barcode")]
    Barcode,
    #[serde(rename = "qr-code")]
    QrCode,
    #[serde(rename = "group")]
    Group,
}
pub const SCHEMA_ID: &str = "https://makersbrain.com/schemas/mb-label-v4.schema.json";
pub const ELEMENT_DISCRIMINATORS: &[&str] = &[
    "text",
    "image",
    "svg",
    "line",
    "rectangle",
    "ellipse",
    "triangle",
    "barcode",
    "qr-code",
    "group",
];
